"""
Issue knowledge base used by seo_common.Audit.

Every issue in every report gets a Description, an Expected / recommended value and a Recommended fix.
A script can pass its own text (audit.add(..., expected=..., fix=...)); otherwise the first rule below whose
pattern matches the issue name (case-insensitive regex search) fills them in. Keep the more specific
patterns above the general ones.

  (pattern, description, expected value, recommended fix)
"""
import re

RULES = [
    # ------------------------------------------------------------------ Lighthouse (12b) - first, so generic rules don't win
    (r"lighthouse could not audit",
     "Lighthouse could not finish auditing the page (it timed out, crashed or the page failed to load), so no "
     "Lighthouse scores exist for it.",
     "A completed Lighthouse run",
     "Open the page in Chrome and check it loads without errors; re-run 12b with a higher --timeout or fewer "
     "--browser-workers."),
    (r"lighthouse .* score (poor|needs improvement)",
     "The page's Lighthouse category score (0-100, the same score PageSpeed Insights shows) is below the green range.",
     ">= 90 / 100",
     "Fix the failed Lighthouse audits listed for this URL (Issue names starting with 'Lighthouse:'), most heavily "
     "weighted first: LCP, TBT and CLS for Performance."),
    # ------------------------------------------------------------------ QA checks 22-29 (kept above the generic rules)
    # 22 business info
    (r"tel: link doesn't match|mailto: link doesn't match",
     "The link dials / emails something different from what the visitor reads - calls and leads go to the wrong place.",
     "The href is the exact number / address that is displayed",
     "Fix the href (or the text) so both use the confirmed number / address from one shared constant."),
    (r"invalid tel: link|invalid mailto: link",
     "The tel: / mailto: link is malformed, so tapping it does nothing or opens an error.",
     "tel:+<country code><digits>  /  mailto:name@domain",
     "Build the href from the digits only (e.g. tel:+919512815630)."),
    (r"not a clickable tel: link|not a clickable mailto: link",
     "A phone number / email address is written on the page but can't be tapped. On phones visitors expect to tap it.",
     "Wrapped in <a href=\"tel:...\"> / <a href=\"mailto:...\">",
     "Wrap the text in a tel: / mailto: link (reuse the site's phone / email link component)."),
    (r"confirmed (phone|email|address).* not found",
     "The confirmed contact detail from qa_config.json does not appear anywhere on the site.",
     "The confirmed value shown in the header / footer / contact page",
     "Update the contact data (site config / footer) to the confirmed value - or fix qa_config.json if it changed."),
    (r"phone number differs from the confirmed|other phone number on the site|several phone numbers",
     "A different phone number is shown than the confirmed one (old number, tracking number, typo, or another office).",
     "Only the confirmed number(s) in header, footer and contact page",
     "Replace it with the confirmed number, or add it to qa_config.json phones if it is a real second line."),
    (r"no clickable phone number in the header|no visible phone number in the desktop header|no tap-to-call",
     "Visitors can't call from the top of the page. For local / legal businesses the phone in the header is a key "
     "conversion point.",
     "The main phone number as a visible tel: link in the desktop and mobile header",
     "Add the phone link to the header component (and a phone icon button in the mobile header)."),
    (r"(phone|email) in json-ld is not shown",
     "Structured data advertises contact details that the page doesn't show - search engines may distrust the markup.",
     "JSON-LD telephone / email = the values on the page",
     "Use the same constant for the JSON-LD and the visible contact details."),
    (r"email in header / footer differs",
     "The header / footer shows an email address that is not the confirmed one.",
     "The confirmed address (qa_config.json emails)", "Replace the address in the shared contact data."),
    (r"address differs from the rest of the site",
     "This page shows a different address than most pages (old office, typo, different format).",
     "The same address, formatted like the Google Business Profile, on every page",
     "Use one shared address component / constant."),
    (r"business name written differently|no organization name in json-ld",
     "The business name differs between the Organization schema, og:site_name, title suffix and copyright line. "
     "Consistent naming helps Google connect the site with the business profile.",
     "One spelling of the business name everywhere",
     "Set the name once (site config) and use it for metadata, schema and the footer."),
    (r"no <footer> on page|footer has no '",
     "The footer is missing or lacks a required link (privacy, terms, disclaimer ...). Legal pages must be reachable "
     "from every page.", "Footer with links to the required legal pages",
     "Add the link to the shared footer component."),
    (r"footer link is broken", "A link in the shared footer returns an error - it is broken on every page.",
     "HTTP 200", "Fix the href or create the page."),
    (r"copyright year is out of date|copyright notice has no year|no copyright notice",
     "The copyright line is missing or shows an old year, which makes the site look unmaintained.",
     "© <current year> <business name>", "Render the year with new Date().getFullYear() in the footer."),
    (r"social link points to the network homepage|social profile link is broken|expected social profile|no social profile links",
     "A social icon doesn't lead to the business's profile (network homepage, share URL, broken or missing).",
     "Links to the real, live profiles", "Put the profile URLs in the footer / site config; confirm them with the client."),
    # 23 forms
    (r"empty form is submitted|invalid email address is accepted",
     "The form sends incomplete or invalid data - leads arrive without a way to reply, spam gets through.",
     "Submission blocked until required fields are valid",
     "Validate before sending (required fields, email format) and show the errors next to the fields."),
    (r"no error message when submitting an empty form",
     "Submitting the empty form gives no visible feedback, so visitors don't know what is wrong.",
     "Each missing field marked (aria-invalid) with an error message",
     "Show field-level errors (role=alert or aria-describedby) and set aria-invalid on the fields."),
    (r"focus doesn't move to the first invalid field",
     "After a failed submit the keyboard / screen-reader focus stays on the button; users must hunt for the error.",
     "Focus moves to the first invalid field", "Call .focus() on the first invalid field after validation."),
    (r"form not visible in chrome",
     "The form exists in the HTML but wasn't visible on load (closed modal / tab), so its validation wasn't tested.",
     "Form tested", "Test it by hand, or open the modal and re-run 23."),
    (r"lead form has no (email|name) field",
     "A contact / lead form doesn't ask for a name or email, so the business can't reply to the lead.",
     "Name, Email (and Phone if the business calls back)", "Add the missing field."),
    (r"lead form on a legal / utility page",
     "Privacy, terms, thank-you and 404 pages should not show a lead form.", "No form on these pages",
     "Hide the form / CTA block on these routes."),
    (r"no privacy notice / link at the lead form",
     "Forms that collect personal data should tell visitors how it is used (GDPR / privacy laws).",
     "A short notice with a link to the privacy policy at the form", "Add the notice under the submit button."),
    (r"disclaimer checkbox", "Legal sites must make visitors confirm they read the disclaimer before contacting.",
     "A required checkbox linking to the disclaimer page", "Add the checkbox (required) with the link."),
    (r"no spam protection on the form", "Without a CAPTCHA or honeypot the form will collect spam.",
     "reCAPTCHA / hCaptcha / Turnstile or a hidden honeypot field",
     "Configure the CAPTCHA key for this environment or add a honeypot field."),
    (r"form posts over insecure|sends personal data with get",
     "Personal data is sent insecurely or ends up in URLs, browser history and server logs.",
     "method=post to an https endpoint", "Change the form method / action."),
    (r"thank-you redirect page is broken", "After submitting, visitors land on an error page.", "HTTP 200",
     "Create the thank-you page or fix the _next / redirect value."),
    (r"form field has no name or id|field without a name is not submitted",
     "Fields without a name are not sent with a native form submission (and get no label in the email).",
     'name="Name" / "Email" / "Phone Number"', "Add name attributes (they become the field labels in the email)."),
    (r"required field not marked in its label|field label not capitalised",
     "Labels should say clearly what to enter and which fields are required.",
     "Capitalised labels, '*' or '(required)' on required fields", "Update the label text."),
    (r"email field is not type=email|phone field is not type=tel|no autocomplete attribute",
     "The field type / autocomplete tells phones which keyboard to show and lets browsers fill it in.",
     "type=email / type=tel and autocomplete=email / tel / name", "Set type and autocomplete on the input."),
    (r"form has no submit button|submit button has no text",
     "The form can't be submitted, or its button has no accessible name.", "A <button type=submit> with text",
     "Add a submit button with a visible label."),
    (r"site search returns no results", "Searching a common word returns nothing - search is broken or unindexed.",
     "Matching pages listed", "Check the search index / API and the results page."),
    # 24 navigation
    (r"desktop dropdown doesn't open|dropdown menu runs off the screen",
     "A desktop menu item that should open a sub-menu doesn't (or the sub-menu is partly off-screen).",
     "The sub-menu opens on hover / click and stays inside the window", "Fix the dropdown component / its CSS position."),
    (r"menu link is broken", "A link in the header menu returns an error - broken on every page.", "HTTP 200",
     "Fix the href in the navigation data."),
    (r"expected menu item missing", "An item listed in qa_config.json nav_expected is not in the header menu.",
     "Every expected item in the menu", "Add the item to the navigation data (or update nav_expected)."),
    (r"no mobile menu button|mobile menu button is hidden|outside the screen|mobile menu doesn't open",
     "Phone visitors can't open the navigation (button missing, hidden, off-screen or not working).",
     "A visible menu button inside the screen that opens the menu",
     "Fix the header layout at this width (button position / overflow) and the menu toggle."),
    (r"mobile menu links are cut off", "Links in the opened mobile menu are partly off-screen or clipped.",
     "Every menu label fully visible", "Fix the drawer position / width and allow labels to wrap."),
    (r"mobile sub-menu doesn't open", "A sub-menu toggle inside the mobile menu does nothing.",
     "Tapping it reveals the sub-menu links", "Fix the accordion / toggle handler."),
    (r"mobile menu can't be closed|doesn't close with escape",
     "The opened mobile menu can't be closed (or not with the Escape key) - visitors get stuck.",
     "Closes with its button, a close button and Escape", "Add a close handler for Escape and the button."),
    (r"missing from the mobile menu|mobile menu has links the desktop",
     "The mobile menu doesn't offer the same pages as the desktop menu, so phone visitors can't reach them.",
     "The same set of pages in both menus", "Render both menus from the same navigation data."),
    (r"horizontal scrolling at \d+% zoom",
     "At this browser zoom the page scrolls sideways - text doesn't reflow (WCAG 1.4.4 / 1.4.10).",
     "No horizontal scrollbar at 120% and 200% zoom", "Fix the element named in Element (fixed widths / min-width)."),
    (r"(javascript error|horizontal scrolling|page failed to load) in (firefox|webkit)",
     "The page behaves differently in another browser engine (Firefox / Safari).", "Same result as in Chrome",
     "Reproduce it in that browser and fix the incompatible code / CSS."),
    # 26 text quality
    (r"^(title|h1) (in all caps|all lowercase)|extra spaces in the",
     "The title / heading isn't written in normal case or has stray spaces; it looks careless in search results.",
     "Title Case or Sentence case, single spaces", "Fix the text in the page metadata / content."),
    (r"repeated word|missing space after punctuation|possible grammar slip",
     "A small writing slip (repeated word, missing space, grammar) - often from templates joining strings.",
     "Clean text", "Fix the text, or the template that builds it."),
    # 27 assets
    (r"json-ld .* has the wrong format|is not an iso 8601 date|datemodified is before datepublished",
     "A structured-data value has the wrong format, so Google may ignore it for rich results.",
     "Absolute https URLs, ISO 8601 dates, headline <= 110 characters", "Fix the value where the JSON-LD is built."),
    (r"font-display not set|no font is preloaded",
     "Text may stay invisible while the font downloads, and the main font is discovered late.",
     "font-display: swap and a preload for the main font", "Load the font with next/font (does both)."),
    (r"favicon\.ico has no|apple-touch-icon is not|manifest icon|manifest has no",
     "An icon file is missing or has the wrong size, so browsers / phones show a blurry or default icon.",
     "favicon 16/32/48, apple-touch-icon 180x180 PNG, manifest 192 + 512", "Export the icons from the design file."),
    (r"logo is low resolution", "The logo bitmap is smaller than 2x its displayed size, so it looks blurry on retina screens.",
     "Bitmap >= 2x the displayed width, or SVG", "Export the logo at 2x (or use SVG)."),
    (r"feed (is broken|is not valid|has no entries)|feed links point|has no rss",
     "The RSS / Atom feed is broken, empty or points to a development host.", "A valid feed listing the posts",
     "Generate the feed from the posts (e.g. a route handler for /feed.xml)."),
    (r"linked pdf is broken|pdf has no|pdf can.t be opened|large pdf", "A linked PDF is broken, very large, untitled or a scanned image without text.",
     "Working, titled, text-based PDFs", "Replace the PDF with an optimised, OCR'd version with a title."),
    # 28 repo
    (r"readme", "The README doesn't explain this project (or is the template text).",
     "Project description + install / dev / build / deploy commands", "Write the README for this project."),
    (r"gitignore|lockfile|\.env\.example",
     "The repository setup is incomplete (ignored files, lockfile, env example).", "A clean, reproducible repo",
     "Add the missing rule / file."),
    (r"no '\w+' script in package\.json|unpinned dependency|typescript check failed",
     "The project's package setup can't be built / reproduced reliably.", "build / start / lint scripts, pinned versions",
     "Fix package.json."),
    # 29 live vs dev
    (r"live url ends in a redirect loop|live page redirects to the homepage",
     "An old URL doesn't lead to its new page - visitors and rankings from that URL are lost.",
     "A 301 to the most relevant new page", "Add a specific redirect for this path."),
    (r"noindex on the new site but indexed on live",
     "The page was indexed on the live site but is noindex on the new site - it will drop out of Google.",
     "index, follow", "Remove the noindex (metadata robots) for this page."),
    (r"changed from the live site|meta description lost|h2 sections are missing|structured data types lost",
     "The new page differs from the live page in an SEO-relevant way (title, H1, description, sections, schema).",
     "Same as live, or an SEO sign-off for the change", "Restore it, or get SEO approval (qa.py mark ... pass)."),
    (r"visual difference from the live page", "How much the first screen differs from the live page (redesigns differ "
     "a lot; migrations should differ little).", "Reviewed", "Look at the *_diff.png in the screenshots folder."),
    # 05 additions
    (r"placeholder link \(href=\"#\"\)", "A link that goes nowhere (href=\"#\") - a leftover placeholder or a button "
     "written as a link.", "A real URL, or a <button> for actions", "Set the real href or change it to a button."),
    (r"in-page anchor points to a missing id", "An in-page link (#section) points to an id that doesn't exist on the page.",
     "An element with that id", "Fix the href or add the id to the target section."),
    # ------------------------------------------------------------------ crawl / status / redirects
    (r"broken internal url|page returns|page not reachable|broken page|sitemap url is not 200",
     "The URL does not return a working page (HTTP error, timeout or connection failure). Visitors and search engines "
     "hit an error and any ranking signals pointing here are lost.",
     "HTTP 200 for every live page",
     "Restore the page, or 301-redirect the URL to the closest live page and update every link that points to it."),
    (r"5xx server error",
     "The server crashed while rendering this page. Search engines retry, then drop the page from the index.",
     "HTTP 200",
     "Check the server / Next.js logs for this route, fix the exception (often missing data in generateMetadata or "
     "the page component) and add error handling."),
    (r"redirect loop",
     "The URL redirects in a circle and never reaches a page. Browsers show an error and crawlers give up.",
     "At most one redirect, ending in an HTTP 200 page",
     "Fix the redirect rules (next.config redirects, middleware, hosting) so the chain ends at a real page."),
    (r"redirect chain",
     "The URL passes through more than one redirect before reaching the page. Each hop wastes crawl budget, slows "
     "visitors and can lose link equity.",
     "A single 301/308 redirect, or a direct link to the final URL",
     "Point the first redirect straight at the final URL and update links to use the final URL."),
    (r"internal link redirects|internal url redirects|sitemap url redirects|^url redirects",
     "The URL redirects to another URL. Linking to (or listing) a redirecting URL costs an extra request and dilutes "
     "link signals.",
     "Links and sitemap entries point directly at the final URL (HTTP 200)",
     "Replace the link / sitemap entry with the final URL shown in Current value."),
    (r"blocked by robots\.txt",
     "robots.txt forbids crawling this URL, so search engines cannot read it.",
     "Indexable pages are allowed in robots.txt",
     "Remove or narrow the Disallow rule that matches this URL (Current value), or remove the URL from the sitemap / "
     "internal links if it should stay private."),
    (r"missing from (the )?sitemap",
     "The page is live and linked on the site but is not listed in sitemap.xml, so search engines may discover it late.",
     "Every indexable page listed in sitemap.xml",
     "Add the route to src/app/sitemap.ts (or its data source) and rebuild."),
    (r"not linked from any page|orphan page",
     "No crawled page links to this URL; it can only be found through the sitemap. Orphan pages get little authority "
     "and are often treated as unimportant.",
     "At least one contextual internal link from a related page",
     "Link to the page from its hub/listing page, navigation, related-content blocks or breadcrumbs."),
    (r"linked only from javascript menus",
     "The only links to this page are inside menus, tabs or accordions that are rendered after a click or hover. "
     "Search engines render pages but don't click, so they may never find the page through the site's links.",
     "At least one plain <a href> link in the server-rendered HTML",
     "Render every menu / tab panel in the HTML (hide inactive ones with CSS or the hidden attribute instead of not "
     "rendering them), or link the page from its hub page, footer or related-content blocks."),
    (r"links rendered only after clicking",
     "Some links (e.g. the inactive tabs of the header mega menu) only exist in the page after a click or hover. "
     "Search engines don't click, so these links pass no link signals and can't be used for discovery.",
     "All navigation links present in the server-rendered HTML",
     "Render all menu / tab panels on the server and toggle their visibility with CSS (or the hidden attribute) "
     "instead of mounting them only when opened."),
    (r"not reachable from homepage",
     "No chain of links leads from the homepage to this page.",
     "Every page reachable by following links from the homepage",
     "Link the page from its section hub or another page that is itself linked from the homepage."),
    (r"page too deep|crawl depth",
     "The page needs many clicks from the homepage. Deep pages are crawled less often and rank worse.",
     "3 clicks or fewer from the homepage",
     "Add links from higher-level pages (hubs, navigation, footer, related content) to shorten the path."),
    (r"non-html|not an html page",
     "An internal link points to a non-HTML resource or the response has no text/html content type.",
     "Internal page links return text/html",
     "Check the link target; serve the page with Content-Type: text/html or link to the right page."),
    (r"crawl limit",
     "The crawler stopped at its page limit, so some URLs were not audited.",
     "All URLs crawled",
     "Re-run with a higher --max-pages value."),

    # ------------------------------------------------------------------ sitemap & robots
    (r"sitemap\.xml missing|sitemap.*invalid",
     "sitemap.xml cannot be read, so search engines can't use it to discover pages.",
     "A valid XML sitemap at /sitemap.xml returning HTTP 200",
     "Add src/app/sitemap.ts returning every public URL, rebuild and confirm /sitemap.xml loads."),
    (r"50,000 urls|larger than 50 mb",
     "The sitemap exceeds the protocol limits and may be ignored.",
     "At most 50,000 URLs and 50 MB per sitemap file",
     "Split it into several sitemaps (generateSitemaps in Next.js) referenced from a sitemap index."),
    (r"not served as xml",
     "The sitemap is served with a non-XML content type.",
     "Content-Type: application/xml (or text/xml)",
     "Serve it through src/app/sitemap.ts (Next.js sets the header) or set the header in the hosting config."),
    (r"local/development host|point to a development|dev(elopment)? host",
     "URLs point to localhost / a development host instead of the live domain.",
     "Absolute https URLs on the production domain",
     "Set NEXT_PUBLIC_SITE_URL to the live https domain for production builds and rebuild."),
    (r"not https|site urls are not https",
     "URLs use http:// instead of https://.",
     "https:// URLs everywhere",
     "Serve the site over HTTPS and build canonical / sitemap / Open Graph URLs from the https domain."),
    (r"mixes hosts|host differs|different host than the sitemap|sitemap on a different host",
     "Different parts of the site disagree about the canonical host (e.g. www vs non-www, or localhost vs live).",
     "One host used by sitemap, canonical, Open Graph and robots.txt",
     "Build every absolute URL from the single NEXT_PUBLIC_SITE_URL value and redirect the other host."),
    (r"duplicate url in sitemap|different letter case",
     "The sitemap lists the same page more than once.",
     "Each URL listed once, in one consistent spelling",
     "De-duplicate the sitemap source data."),
    (r"lastmod",
     "<lastmod> is missing, invalid or in the future, so search engines can't tell when the page changed.",
     "A valid W3C date (YYYY-MM-DD or ISO 8601) not in the future",
     "Set lastModified in sitemap.ts from the content's real update date."),
    (r"robots\.txt missing",
     "There is no robots.txt; crawlers get no rules and no sitemap location.",
     "/robots.txt with User-agent, Allow/Disallow rules and a Sitemap: line",
     "Add src/app/robots.ts returning rules and the absolute sitemap URL."),
    (r"blocks the homepage|whole site",
     "robots.txt blocks the entire site - nothing can be crawled or indexed.",
     "Allow: / for public sites",
     "Remove 'Disallow: /' from the production robots.txt."),
    (r"no sitemap: line|declares the sitemap",
     "robots.txt does not tell crawlers where the sitemap is.",
     "Sitemap: https://<domain>/sitemap.xml",
     "Return sitemap: `${SITE_URL}/sitemap.xml` from robots.ts."),
    (r"declared in robots\.txt is unreachable",
     "The sitemap URL declared in robots.txt doesn't load.",
     "The declared sitemap returns HTTP 200",
     "Fix the Sitemap: line in robots.ts so it matches the real sitemap URL."),
    (r"no user-agent group",
     "robots.txt has rules but no User-agent line, so crawlers may ignore them.",
     "At least one 'User-agent: *' group",
     "Add a User-agent group in robots.ts."),
    (r"sitemap url is noindex|noindex on a sitemap page",
     "The page is listed in the sitemap but tells search engines not to index it - contradictory signals.",
     "Sitemap pages are indexable (no noindex)",
     "Either remove noindex from the page or remove the page from the sitemap."),
    (r"canonicalises elsewhere|canonical points to another url",
     "The page declares a different URL as canonical, so this URL will not be indexed.",
     "Self-referencing canonical on every indexable page",
     "Set alternates.canonical to the page's own URL, or remove this URL from the sitemap/links if it is a duplicate."),

    # ------------------------------------------------------------------ titles / descriptions / headings
    (r"duplicate title",
     "Several pages share the same <title>. Search engines can't tell them apart and may show the wrong page.",
     "A unique title per page",
     "Generate titles from page-specific data in generateMetadata (service / article / project name + brand)."),
    (r"title (missing)|missing title",
     "The page has no <title>, the most important on-page ranking and click-through element.",
     "A unique, descriptive 30-60 character title",
     "Export metadata.title (or generateMetadata) for this route."),
    (r"title too short|title length",
     "The title is outside the recommended length; short titles waste ranking space, long ones are cut off in results.",
     "30-60 characters (ideal 50-60)",
     "Rewrite the title: primary topic first, then a differentiator, then the brand."),
    (r"title too long",
     "The title is longer than Google shows (~60 characters / 600 px) and will be truncated.",
     "30-60 characters (ideal 50-60)",
     "Shorten the title: keep the primary topic first and drop filler words."),
    (r"multiple <title>|<title> inside <body>",
     "The page has more than one <title> (or one in <body>); browsers and search engines may pick the wrong one.",
     "Exactly one <title> inside <head>",
     "Remove manual <title>/<Head> tags and let the Next.js Metadata API render a single title."),
    (r"duplicate description",
     "Several pages share the same meta description, so search snippets look identical.",
     "A unique description per page",
     "Write page-specific descriptions in generateMetadata."),
    (r"(meta )?description missing|missing meta description",
     "The page has no meta description; Google invents a snippet from page text, often poorly.",
     "A unique 70-160 character description (ideal 150-160)",
     "Add metadata.description summarising the page and including its main topic."),
    (r"description too short|description length",
     "The meta description is outside the recommended length.",
     "70-160 characters (ideal 150-160)",
     "Expand / tighten the description: what the page offers, who it's for, and a reason to click."),
    (r"description too long",
     "The meta description is longer than search engines show and will be truncated.",
     "70-160 characters (ideal 150-160)",
     "Shorten the description to ~155 characters, keeping the key message first."),
    (r"multiple meta descriptions|duplicate <meta name=description>",
     "More than one meta description tag on the page.",
     "Exactly one <meta name=\"description\">",
     "Remove manually added meta tags; define description once in metadata."),
    (r"meta keywords",
     "Meta keywords are ignored by Google and reveal your keyword strategy to competitors.",
     "No meta keywords tag",
     "Remove metadata.keywords; put topics in title, H1, body text and alt text instead."),
    (r"missing h1|no headings on page",
     "The page has no H1, the main heading that tells users and search engines what the page is about.",
     "Exactly one descriptive H1",
     "Render the page title as a single <h1> near the top of the main content."),
    (r"multiple h1",
     "The page has more than one H1, which blurs the page's main topic.",
     "Exactly one H1",
     "Keep one H1 for the page title and change the other H1s to H2 (style with CSS, not heading level)."),
    (r"empty h1|empty heading",
     "A heading element contains no text (often icons only or content rendered later).",
     "Every heading has meaningful text",
     "Add text to the heading or replace it with a non-heading element."),
    (r"h1 too short|h1 not meaningful",
     "The H1 is too short to describe the page.",
     "A descriptive H1 of at least 10 characters",
     "Rewrite the H1 to state the page's topic clearly."),
    (r"h1 identical to title",
     "The H1 repeats the <title> word for word; a slightly different H1 can cover more search phrasing.",
     "H1 and title on the same topic but worded differently",
     "Vary the H1 wording (e.g. drop the brand, add a qualifier)."),
    (r"no h2",
     "The page has no H2 sub-headings, so its structure is hard to scan for users and search engines.",
     "Main sections introduced with H2 headings",
     "Add H2 headings for the main sections of the page."),
    (r"first heading is not h1",
     "The first heading on the page is not the H1, so the outline starts at the wrong level.",
     "The first heading in the document is the H1",
     "Move the H1 above other headings or turn earlier headings (e.g. in the header/hero) into non-heading elements."),
    (r"skipped heading level|skipped h",
     "A heading level is skipped going down (e.g. H2 followed by H4), which breaks the document outline for screen "
     "readers and search engines.",
     "Headings descend one level at a time (H1 > H2 > H3)",
     "Change the heading level shown in Current value to the next level down, and style it with CSS."),
    (r"very long heading",
     "The heading is very long, which dilutes its meaning.",
     "Headings under 90 characters",
     "Shorten the heading and move detail into the paragraph below it."),
    (r"duplicate heading text",
     "The same heading text appears more than once on the page.",
     "Unique heading text per section",
     "Reword repeated headings so each section is distinct."),
    (r"page topic not in title|page topic not in h1|title and h1 share no topic|description doesn't mention",
     "The page's topic (taken from the URL slug / title) is missing from this element, weakening relevance signals.",
     "The main topic words appear in URL, title, H1 and description",
     "Include the page's primary topic words naturally in the element named in Issue."),
    (r"url not seo-friendly|seo-friendly slug|uppercase letters in url|underscores/spaces|sitemap url has parameters",
     "The URL is harder to read or share (uppercase, underscores, encoded characters, IDs, parameters or too long/deep).",
     "Short, lowercase, hyphen-separated, descriptive URLs without parameters",
     "Rename the route/slug (e.g. /blog/my-article), and 301-redirect the old URL to the new one."),
    (r"trailing slash in sitemap",
     "The sitemap URL uses a trailing slash while the site serves URLs without one.",
     "One consistent URL form (no trailing slash in Next.js by default)",
     "Generate sitemap URLs without the trailing slash."),

    # ------------------------------------------------------------------ canonical / indexing / duplicates
    (r"missing canonical",
     "The page has no canonical tag, so duplicate URLs (parameters, trailing slash, case) can compete with it.",
     "<link rel=\"canonical\" href=\"<absolute URL of this page>\">",
     "Set alternates: { canonical: '/path' } in the page metadata (metadataBase makes it absolute)."),
    (r"duplicate canonical|multiple canonical",
     "More than one canonical tag; search engines may ignore all of them.",
     "Exactly one canonical tag",
     "Remove the extra canonical (often from a layout plus the page) so only one is rendered."),
    (r"relative canonical|canonical is not absolute|canonical not absolute",
     "The canonical URL is relative.",
     "An absolute https URL",
     "Set metadataBase in the root layout so Next.js renders absolute canonical URLs."),
    (r"canonical is not self-referencing",
     "The canonical points to a different page, so this page will not be indexed.",
     "Canonical = this page's own URL",
     "Fix alternates.canonical for this route."),
    (r"canonical target is not 200|broken canonical",
     "The canonical URL does not return HTTP 200.",
     "Canonical URL returns HTTP 200 directly (no redirect)",
     "Point the canonical at the final, live URL."),
    (r"canonical tag inside <body>",
     "The canonical tag is in <body>, where search engines ignore it.",
     "Canonical inside <head>",
     "Define it through the Metadata API instead of rendering <link> in a component."),
    (r"canonical keeps url parameters",
     "The canonical includes tracking parameters, creating duplicate canonical URLs.",
     "Canonical without query parameters",
     "Build the canonical from the pathname only."),
    (r"duplicate url: .* variant",
     "A variant of the URL (trailing slash / uppercase) serves the same page with HTTP 200 and no canonical back, "
     "creating duplicate content.",
     "Variants 301/308-redirect to the main URL, or canonicalise to it",
     "Keep Next.js trailingSlash handling (redirect) and make sure every page has a self canonical."),
    (r"noindex via|'none'",
     "The page tells search engines not to index it.",
     "Indexable pages: no noindex (meta robots, googlebot or X-Robots-Tag)",
     "Remove robots: { index: false } / the X-Robots-Tag header for pages that should rank."),
    (r"nofollow via|nofollow on page",
     "The page tells search engines not to follow its links, so link equity stops here.",
     "index, follow",
     "Remove nofollow from the page's robots metadata."),
    (r"no explicit robots meta",
     "No robots meta tag; search engines default to index, follow (fine), but intent isn't documented.",
     "Optional: <meta name=\"robots\" content=\"index, follow\">",
     "Optionally add robots: { index: true, follow: true } to the root metadata."),
    (r"soft 404|unknown urls don't return 404",
     "Unknown URLs return a normal page instead of HTTP 404, so search engines index error pages.",
     "HTTP 404 for unknown URLs",
     "Call notFound() for missing data and keep app/not-found.tsx returning the default 404 status."),
    (r"404 page offers few links",
     "The 404 page gives visitors few ways back into the site.",
     "404 page with navigation, search or links to main sections",
     "Add helpful links (home, services, blog, contact) to app/not-found.tsx."),
    (r"404 page is not noindex",
     "The 404 page has no noindex.",
     "noindex on the 404 page",
     "Add robots: { index: false } to the not-found page metadata."),
    (r"http does not redirect to https|http -> https",
     "http:// requests are not permanently redirected to https://.",
     "301/308 redirect from http:// to https://",
     "Enable 'force HTTPS' in the hosting/CDN settings."),
    (r"www and non-www",
     "Both www and non-www serve the site, creating two copies of every page.",
     "One host; the other permanently redirects to it",
     "Add a host redirect in the hosting/CDN config."),
    (r"duplicate content|identical text|duplicate page content",
     "The main text is identical to another page, so search engines pick one and ignore the others.",
     "Unique main content on every indexable page",
     "Write unique content, merge the pages (301-redirect one), or canonicalise the copy to the original."),
    (r"near-duplicate",
     "The page's text is at least 90% similar to another page (Current value).",
     "Each page substantially unique (< 90% similar)",
     "Add page-specific content (examples, FAQs, data) or merge the near-identical pages."),
    (r"paragraph repeated on many pages",
     "The same paragraph appears on many pages (boilerplate), diluting each page's unique content.",
     "Boilerplate kept short; main content unique per page",
     "Shorten or vary the repeated paragraph, or move it to a shared component outside <main>."),

    # ------------------------------------------------------------------ content
    (r"empty page",
     "The page has almost no text in <main>, so it has nothing to rank for.",
     "300+ words of useful content (50 words absolute minimum)",
     "Add real content, or noindex / remove the page if it has no value."),
    (r"very short page|thin content",
     "The page has little text in <main>; thin pages rarely rank.",
     "300+ words of useful content",
     "Expand the content: explain the topic, add examples, FAQs, benefits, process, results."),
    (r"placeholder|debug / placeholder|test text",
     "Placeholder / test text is visible to visitors (Current value).",
     "Final, real copy only",
     "Replace the placeholder text in the page source or CMS data."),
    (r"generic ai|filler phrasing",
     "The copy uses generic filler phrases that read as low-effort and add no information.",
     "Specific, concrete wording",
     "Rewrite the listed phrases with concrete facts, numbers and examples."),
    (r"article without author",
     "Articles without an author are weaker E-E-A-T (experience, expertise, authority, trust) signals.",
     "A visible author plus author in Article/BlogPosting schema",
     "Show the author on the article and add author to the JSON-LD and metadata.authors."),
    (r"without publication date",
     "The article has no publication date.",
     "datePublished in schema and article:published_time",
     "Add publishedTime to openGraph metadata and datePublished to the JSON-LD."),
    (r"without updated date",
     "The article has no dateModified, so freshness can't be judged.",
     "dateModified in schema",
     "Add dateModified (and openGraph modifiedTime) from the content's update date."),
    (r"very difficult to read",
     "The text is very hard to read (low Flesch score).",
     "Flesch Reading Ease 50+",
     "Use shorter sentences and simpler words; break long paragraphs up."),
    (r"long sentences",
     "Sentences are long on average, which hurts readability.",
     "Average under 20-25 words per sentence",
     "Split long sentences and use bullet lists."),

    # ------------------------------------------------------------------ links
    (r"broken internal link",
     "A link on this page points to an internal URL that returns an error.",
     "Every internal link returns HTTP 200",
     "Fix or remove the link (Current value shows the target) or restore / redirect the target page."),
    (r"broken external link",
     "A link on this page points to an external URL that returns an error.",
     "External links return HTTP 200 (or a redirect to a working page)",
     "Update the link to the current URL or remove it."),
    (r"external link redirects|third-party url redirects",
     "An external link redirects to another URL.",
     "Links point to the final URL",
     "Replace the link with the final URL shown in Expected value."),
    (r"empty link|javascript: link",
     "An <a> element has no usable href (empty or javascript:), so it isn't a real link for crawlers or keyboard users.",
     "<a href> pointing to a real URL; use <button> for actions",
     "Give the link a real href or change it to a <button>."),
    (r"link without (text|accessible)",
     "The link has no text or accessible name, so screen readers announce only 'link' and search engines get no anchor text.",
     "Descriptive link text or aria-label",
     "Add visible text, an aria-label, or alt text on the image inside the link."),
    (r"non-descriptive anchor",
     "The anchor text ('read more', 'click here') says nothing about the target page.",
     "Anchor text that describes the target (e.g. 'Read the React migration case study')",
     "Rewrite the link text, or add an aria-label with the descriptive text."),
    (r"nofollow on an internal link",
     "An internal link is nofollow, which stops link equity flowing within your own site.",
     "Internal links without rel=nofollow",
     "Remove rel=\"nofollow\" from internal links."),
    (r"target=_blank without rel=noopener",
     "A link opens a new tab without rel=noopener, letting the opened page control this tab (tab-nabbing).",
     "rel=\"noopener noreferrer\" on target=_blank links",
     "Add rel=\"noopener noreferrer\" to the link."),
    (r"excessive links",
     "The page has a very large number of links, diluting the value passed by each.",
     "Under ~150 links per page",
     "Reduce navigation/footer duplication and link only to the most relevant pages."),
    (r"no internal links|very few internal links|few internal links",
     "The page links to few or no other pages on the site, making it a dead end for users and crawlers.",
     "At least 3 contextual internal links",
     "Add links to related services, articles, case studies and the contact page."),
    (r"nested page without breadcrumbs",
     "A nested page has no breadcrumb navigation.",
     "Breadcrumbs (nav aria-label=\"breadcrumb\") on nested pages",
     "Add a breadcrumb component plus BreadcrumbList JSON-LD."),
    (r"homepage doesn't link to main section",
     "The homepage does not link to a main section of the site.",
     "Homepage links to every main section",
     "Add the section to the header navigation or a homepage block."),
    (r"hub page doesn't link",
     "The section hub page doesn't link to all of its detail pages.",
     "Hub page links to every detail page",
     "List all detail pages on the hub (grid, list or paginated list)."),

    # ------------------------------------------------------------------ images
    (r"missing alt|image without alt",
     "The image has no alt attribute. Screen readers read the file name and search engines get no description.",
     "alt=\"<what the image shows>\" (or alt=\"\" for purely decorative images)",
     "Add a short, descriptive alt to the <Image> / <img> shown in Element."),
    (r"empty alt",
     "The image has an empty alt, which is only correct when it is purely decorative.",
     "A descriptive alt for meaningful images; alt=\"\" only for decoration",
     "Add descriptive alt text, or mark decorative images aria-hidden=\"true\"."),
    (r"generic alt|very short alt|alt text is a file name|keyword-stuffed alt|alt text longer",
     "The alt text is unhelpful (generic, too short, a file name, keyword-stuffed or too long).",
     "A natural description of the image, about 5-125 characters",
     "Rewrite the alt to describe what the image shows in context."),
    (r"duplicate alt",
     "Several images on the page share the same alt text.",
     "Alt text specific to each image",
     "Describe each image individually."),
    (r"broken image|broken .*image",
     "The image URL returns an error, so a broken image is shown.",
     "Image URL returns HTTP 200 with an image content type",
     "Fix the src path or restore the file in /public."),
    (r"oversized|image pixels much larger",
     "The image file is larger than needed, slowing the page.",
     "Under ~300 KB per image, sized to its display size",
     "Compress the image, serve WebP/AVIF through next/image and provide correct sizes."),
    (r"served as (jpeg|png|gif)",
     "The image is served in an older format.",
     "WebP or AVIF",
     "Use next/image (with images.formats ['image/avif','image/webp']) or convert the source file."),
    (r"missing width/height",
     "The image has no width/height, so the layout jumps when it loads (CLS).",
     "width and height attributes (or next/image fill inside a sized container)",
     "Pass width/height to <Image> or use fill with a sized parent."),
    (r"below-the-fold image not lazy",
     "An image far down the page loads immediately, competing with above-the-fold content.",
     "loading=\"lazy\" on images below the fold",
     "Use next/image (lazy by default) and remove priority/eager from non-hero images."),
    (r"first .*image is lazy",
     "The hero / LCP image is lazy-loaded, delaying Largest Contentful Paint.",
     "Eager loading with fetchpriority=high for the LCP image",
     "Add priority to the hero <Image>."),
    (r"no srcset",
     "The image has no srcset, so phones download the desktop-size file.",
     "srcset/sizes (automatic with next/image)",
     "Use next/image with a sizes prop."),
    (r"non-descriptive file name|file name not lowercase",
     "The image file name is not descriptive / not lowercase-hyphenated.",
     "Descriptive lowercase-hyphenated file names (e.g. react-dashboard-screenshot.webp)",
     "Rename the file and update references."),
    (r"raw <img>|images not using next/image",
     "Plain <img> tags skip Next.js image optimisation (resizing, WebP/AVIF, lazy loading).",
     "next/image for content images",
     "Replace <img> with <Image> from next/image."),

    # ------------------------------------------------------------------ social
    (r"missing og:|missing twitter:|no twitter metadata",
     "A social sharing tag is missing, so shared links look generic or pick random text/images.",
     "Complete Open Graph and Twitter tags on every page",
     "Fill openGraph and twitter in the page's metadata (Next.js renders the tags)."),
    (r"og:image.*not 1200x630|og:image size|twitter:image.*not 1200x630",
     "The share image has the wrong size/aspect ratio and will be cropped or shown small.",
     "1200x630 px (1.91:1)",
     "Create a 1200x630 image (or app/opengraph-image.tsx) for the page."),
    (r"image is svg",
     "Social networks don't render SVG share images.",
     "PNG or JPEG share image",
     "Use a PNG/JPEG for og:image and twitter:image."),
    (r"larger than 5 mb",
     "The share image is too large for some networks.",
     "Under 5 MB (ideally < 300 KB)",
     "Compress the share image."),
    (r"not an absolute url|og:url is not absolute|og:image not absolute",
     "The URL in the tag is relative; social networks require absolute URLs.",
     "Absolute https URL",
     "Set metadataBase in the root layout."),
    (r"og:url differs from canonical",
     "og:url and the canonical URL disagree.",
     "og:url = canonical URL",
     "Set openGraph.url to the same value as alternates.canonical."),
    (r"og:image:width/height don't match",
     "The declared og:image dimensions don't match the real image.",
     "og:image:width / og:image:height equal the real pixel size",
     "Fix the width/height values in openGraph.images."),
    (r"og:title much shorter",
     "og:title is much shorter than the page title.",
     "og:title as descriptive as the title",
     "Use the page title (or a share-optimised variant) as og:title."),
    (r"duplicate og:title",
     "Several pages share the same og:title.",
     "Unique og:title per page",
     "Generate openGraph.title per page."),
    (r"same share image on most pages",
     "Most pages share one generic share image.",
     "Page-specific share images for key pages",
     "Add opengraph-image.tsx per route segment or per-page openGraph.images."),
    (r"twitter:card is not",
     "The Twitter card type is not the large-image card.",
     "twitter:card = summary_large_image",
     "Set twitter: { card: 'summary_large_image' }."),
    (r"missing og:image:width",
     "og:image has no declared width/height, so networks must download it before rendering a preview.",
     "og:image:width and og:image:height",
     "Pass width/height in openGraph.images."),

    # ------------------------------------------------------------------ structured data
    (r"json-ld parse error|invalid json-ld",
     "A JSON-LD block is not valid JSON, so search engines ignore it.",
     "Valid JSON in every application/ld+json script",
     "Render JSON-LD with JSON.stringify(data) instead of hand-written strings."),
    (r"missing or wrong @context",
     "The JSON-LD has no schema.org @context.",
     "\"@context\": \"https://schema.org\"",
     "Add @context to the top-level JSON-LD object."),
    (r"no json-ld",
     "The page has no structured data, so it can't earn rich results.",
     "JSON-LD describing the page (WebPage / Service / Article ...)",
     "Add a <script type=\"application/ld+json\"> with the matching schema.org type."),
    (r"missing .* schema$|missing breadcrumblist",
     "The page lacks the structured-data type expected for this kind of page.",
     "The schema.org type named in Expected value",
     "Add JSON-LD of that type with its required properties."),
    (r"faq section without faqpage",
     "The page has an FAQ section but no FAQPage schema.",
     "FAQPage JSON-LD with each question and answer",
     "Generate FAQPage JSON-LD from the same FAQ data the page renders."),
    (r"address shown but no localbusiness",
     "An address is shown but there is no LocalBusiness/ProfessionalService schema.",
     "LocalBusiness or ProfessionalService with address, telephone, geo",
     "Add LocalBusiness JSON-LD to the contact page / home page."),
    (r"missing required properties",
     "A schema object lacks required properties, so it is invalid for rich results.",
     "All required properties present",
     "Add the properties listed in Current value."),
    (r"missing recommended properties",
     "A schema object lacks recommended properties that improve rich results.",
     "Recommended properties present",
     "Add the properties listed in Current value."),
    (r"breadcrumblist has fewer|breadcrumb item missing",
     "The BreadcrumbList is incomplete.",
     "2+ ListItems, each with position, name and item",
     "Build breadcrumb JSON-LD from the full path."),
    (r"faq question without",
     "An FAQ entry has no question name or accepted answer.",
     "Question.name and acceptedAnswer.text on every entry",
     "Fill both fields from the FAQ data."),
    (r"identical json-ld block repeated|appears more than once|same @id",
     "The same structured data is output more than once.",
     "Each entity defined once",
     "Render the JSON-LD in one place (layout or page, not both)."),

    # ------------------------------------------------------------------ hreflang / languages
    (r"no hreflang tags|language missing from hreflang|hreflang alternates missing",
     "hreflang annotations are missing, so search engines may show the wrong language version.",
     "rel=alternate hreflang for every language plus x-default",
     "Set alternates.languages in metadata for every page."),
    (r"missing x-default",
     "No x-default hreflang for users whose language isn't covered.",
     "hreflang=\"x-default\" pointing at the default page",
     "Add 'x-default' to alternates.languages."),
    (r"no self-referencing hreflang",
     "The page's hreflang set doesn't include the page itself.",
     "hreflang set includes the current page",
     "Include the current language URL in alternates.languages."),
    (r"invalid hreflang",
     "The hreflang code is not a valid ISO 639-1 language / ISO 3166-1 country code.",
     "Codes like en, it, de, en-GB, x-default",
     "Correct the code (e.g. en-GB, not en-UK)."),
    (r"hreflang url is not absolute",
     "The hreflang URL is relative.",
     "Absolute URLs in hreflang",
     "Set metadataBase so alternates render absolute URLs."),
    (r"hreflang alternate not 200|broken hreflang",
     "An hreflang alternate URL does not return HTTP 200.",
     "Every alternate returns HTTP 200",
     "Fix the alternate URL or remove it."),
    (r"missing return link",
     "The alternate page doesn't link back with hreflang, so search engines ignore the pair.",
     "Reciprocal hreflang links between all language versions",
     "Output the same alternates.languages set on every language version."),
    (r"duplicate hreflang code|same url used for several languages",
     "hreflang annotations conflict (same code twice or one URL for several languages).",
     "One URL per language code",
     "De-duplicate alternates.languages."),
    (r"not available in",
     "The page fails when requested in this language.",
     "HTTP 200 in every supported language",
     "Add the missing translations / route for this language."),
    (r"untranslated|not translated",
     "The language version shows English content / metadata.",
     "Translated content and metadata",
     "Add translations for the page content, title and description."),
    (r"html lang",
     "<html lang> is missing or doesn't match the language served.",
     "<html lang> matching the page language (e.g. en, it)",
     "Set the lang attribute in the root layout from the active locale."),
    (r"vary: cookie",
     "The language is chosen by cookie but responses don't send Vary: Cookie, so CDNs may cache one language for all.",
     "Vary: Cookie (or language-specific URLs)",
     "Add Vary: Cookie in middleware/headers, or move languages to URL prefixes."),
    (r"localized page canonicalises to english",
     "Translated pages canonicalise to the English page, so they can't rank in their own language.",
     "Self canonical on each language version + hreflang",
     "Set alternates.canonical to the localized URL."),

    # ------------------------------------------------------------------ technical HTML
    (r"missing <!doctype",
     "No <!DOCTYPE html>, so browsers render in quirks mode.",
     "<!DOCTYPE html> as the first line",
     "Next.js adds it automatically - check custom document/HTML output."),
    (r"missing <(html|head|body)>",
     "A required document element is missing from the HTML.",
     "<html>, <head> and <body> present",
     "Render them from the root layout."),
    (r"missing <meta charset>",
     "No character encoding declared.",
     "<meta charset=\"utf-8\"> in <head>",
     "Next.js adds it by default - check for a custom head override."),
    (r"missing (responsive )?viewport|viewport meta missing",
     "No responsive viewport meta, so phones render the desktop layout zoomed out.",
     "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
     "Export viewport from the root layout (Next.js adds it by default)."),
    (r"duplicate ids",
     "Several elements share the same id, which breaks label/ARIA references and in-page links.",
     "Unique id values",
     "Make the id unique (useId() in React components rendered more than once)."),
    (r"empty buttons",
     "A <button> has no text or accessible name.",
     "Visible text or aria-label on every button",
     "Add text or an aria-label."),
    (r"deprecated <",
     "The page uses a deprecated HTML tag.",
     "Modern semantic HTML + CSS",
     "Replace the tag with semantic HTML and CSS."),
    (r"link nested inside a link|interactive element nested",
     "Interactive elements are nested (link in link / button), which is invalid HTML and breaks clicks and accessibility.",
     "No interactive element inside another",
     "Restructure the card: one link wrapping the card, other actions outside it."),
    (r"block element inside <p>",
     "A block element is inside <p>; browsers rewrite the DOM, which can cause hydration errors.",
     "Only inline content inside <p>",
     "Change the <p> to a <div> or move the block element out."),
    (r"jsx attribute leaked",
     "A React-only attribute (className / htmlFor) appears in the HTML.",
     "Valid HTML attributes",
     "Fix the component that renders raw HTML (dangerouslySetInnerHTML / markdown)."),

    # ------------------------------------------------------------------ accessibility
    (r"svg role=img without a name",
     "An SVG marked role=img has no accessible name.",
     "aria-label, aria-labelledby or <title> on role=img SVGs",
     "Add aria-label, or aria-hidden=\"true\" if decorative."),
    (r"form field without a label",
     "A form field has no label, so screen-reader users don't know what to type (placeholder isn't a label).",
     "<label for> / wrapping <label> / aria-label on every field",
     "Add a visible <label> linked to the field id."),
    (r"button without accessible name",
     "A button has no accessible name (icon-only).",
     "Visible text or aria-label",
     "Add aria-label describing the action."),
    (r"no <main> landmark|more than one main|no <(header|nav|footer)> landmark",
     "Landmark regions are missing or duplicated, so assistive technology can't jump between page regions.",
     "One <main>, plus <header>, <nav>, <footer>",
     "Use semantic landmark elements in the layout."),
    (r"points to a missing id",
     "An ARIA reference points to an id that doesn't exist.",
     "aria-labelledby / aria-describedby / aria-controls reference existing ids",
     "Fix the id or the reference."),
    (r"invalid aria attribute",
     "The element uses an ARIA attribute that doesn't exist.",
     "Only valid aria-* attributes",
     "Fix the typo or remove the attribute."),
    (r"invalid aria role",
     "The element uses an invalid ARIA role.",
     "A valid WAI-ARIA role",
     "Fix or remove the role attribute."),
    (r"aria-hidden on a focusable",
     "A focusable element is hidden from screen readers, so keyboard users focus something they can't hear.",
     "No aria-hidden on focusable elements",
     "Remove aria-hidden or add tabindex=\"-1\"."),
    (r"positive tabindex",
     "A positive tabindex changes the natural focus order.",
     "tabindex 0 or -1 only",
     "Remove the positive tabindex and order the DOM correctly."),
    (r"no skip-navigation",
     "There is no 'skip to content' link for keyboard users.",
     "A 'Skip to main content' link as the first focusable element",
     "Add <a href=\"#main\" class=\"skip-link\"> to the layout."),
    (r"iframe without title",
     "An iframe has no title, so screen readers can't describe it.",
     "title attribute on every iframe",
     "Add a descriptive title."),
    (r"video without captions",
     "A video has no captions track.",
     "<track kind=\"captions\"> for videos with speech",
     "Add a WebVTT captions track."),
    (r"aria-live|role=alert region",
     "Form errors aren't announced to screen-reader users.",
     "An aria-live / role=alert region for form messages",
     "Render error/success messages inside an aria-live=\"polite\" region."),
    (r"^axe-core could not run",
     "The automated accessibility engine couldn't run on this page.",
     "axe-core runs",
     "Install axe-playwright-python or allow loading axe-core from the CDN."),
    (r"tab key doesn't reach",
     "Pressing Tab doesn't reach any element - keyboard users can't use the page.",
     "All interactive elements reachable with Tab",
     "Remove tabindex=-1 / focus traps and use native interactive elements."),
    (r"without a visible focus indicator",
     "Focused elements show no visible focus indicator, so keyboard users lose their place.",
     "A clear :focus-visible outline/ring",
     "Add :focus-visible styles (e.g. focus-visible:ring-2) and don't remove outlines."),
    (r"not reachable by keyboard",
     "An element acts as clickable (pointer cursor) but isn't a link/button, so keyboard users can't use it.",
     "Clickable elements are <a> / <button> (or have role + tabindex + key handlers)",
     "Change the element to a <button> or <a>."),
    (r"touch targets? smaller than 24",
     "Touch targets are smaller than 24x24 px, too small to tap reliably (WCAG 2.5.8).",
     "At least 24x24 px (44x44 recommended)",
     "Increase padding / min-width / min-height of the element."),
    (r"touch targets? smaller than 44",
     "Touch targets are smaller than the recommended 44x44 px.",
     "44x44 px",
     "Increase padding / min-height on the element."),

    # ------------------------------------------------------------------ security
    (r"missing content-security-policy",
     "No Content-Security-Policy header, so injected scripts run without restriction (XSS risk).",
     "A Content-Security-Policy header",
     "Add a CSP in next.config headers() or middleware (start with Report-Only)."),
    (r"missing strict-transport-security|hsts max-age",
     "HSTS is missing or short, so browsers may still connect over plain HTTP.",
     "Strict-Transport-Security: max-age=31536000; includeSubDomains",
     "Add the HSTS header in next.config headers() or at the CDN."),
    (r"x-content-type-options",
     "X-Content-Type-Options is missing or wrong, allowing MIME-type sniffing.",
     "X-Content-Type-Options: nosniff",
     "Add the header in next.config headers()."),
    (r"missing referrer-policy",
     "No Referrer-Policy header; full URLs may leak to other sites.",
     "Referrer-Policy: strict-origin-when-cross-origin",
     "Add the header in next.config headers()."),
    (r"missing permissions-policy",
     "No Permissions-Policy header to disable unused browser features.",
     "Permissions-Policy: camera=(), microphone=(), geolocation=()",
     "Add the header in next.config headers()."),
    (r"clickjacking",
     "The page can be framed by other sites (clickjacking).",
     "X-Frame-Options: DENY or CSP frame-ancestors 'none'",
     "Add one of these headers in next.config headers()."),
    (r"weak csp",
     "The CSP allows 'unsafe-inline' or * for scripts, which weakens XSS protection.",
     "Nonce- or hash-based script-src",
     "Use a nonce-based CSP via middleware."),
    (r"reveals server software",
     "A response header reveals server software / versions.",
     "No version-revealing headers",
     "Set poweredByHeader: false and strip Server versions at the CDN."),
    (r"cookie without secure",
     "A cookie is sent without the Secure flag.",
     "Secure on every cookie over HTTPS",
     "Set secure: true when setting the cookie."),
    (r"cookie without samesite",
     "A cookie has no SameSite attribute.",
     "SameSite=Lax (or Strict)",
     "Set sameSite: 'lax' when setting the cookie."),
    (r"insecure \(http://\)|mixed content",
     "The HTTPS page loads a resource over http:// (mixed content); browsers block or warn.",
     "https:// for every resource",
     "Change the resource URL to https://."),
    (r"subresource integrity",
     "A third-party script has no integrity hash, so a compromised CDN could inject code.",
     "integrity=\"sha384-...\" crossorigin=\"anonymous\"",
     "Add SRI hashes, or self-host the script."),
    (r"sensitive file",
     "A sensitive file is publicly downloadable.",
     "HTTP 404/403 for sensitive files",
     "Remove the file from the public output and block the path."),
    (r"source map is public|productionbrowsersourcemaps",
     "JavaScript source maps are public, exposing original source code.",
     "No public .map files in production",
     "Set productionBrowserSourceMaps: false (default) or upload maps privately to your error tracker."),
    (r"^(ssl certificate|invalid ssl|could not check ssl|old tls)",
     "There is a problem with the site's SSL/TLS certificate or protocol.",
     "A valid certificate with 30+ days left, TLS 1.2+",
     "Renew / fix the certificate at the host and disable old TLS versions."),

    # ------------------------------------------------------------------ performance / CWV
    (r"^lcp |lcp (poor|needs)",
     "Largest Contentful Paint is slow: the main content appears late.",
     "LCP <= 2.5 s",
     "Optimise the LCP element (Element): priority on the hero image, smaller image, less render-blocking CSS/JS, faster TTFB."),
    (r"^inp |slow interaction",
     "Interactions respond slowly (INP).",
     "INP <= 200 ms",
     "Break up long JavaScript tasks, reduce hydration work, defer third-party scripts."),
    (r"^cls |layout shift",
     "Content moves while loading (Cumulative Layout Shift).",
     "CLS <= 0.1",
     "Give images/embeds fixed dimensions, reserve space for dynamic content, use font-display: optional/swap with next/font."),
    (r"^fcp ",
     "First Contentful Paint is slow.",
     "FCP <= 1.8 s",
     "Reduce render-blocking resources and server response time."),
    (r"ttfb",
     "The server takes long to send the first byte.",
     "TTFB <= 800 ms",
     "Use static generation / caching (generateStaticParams, revalidate), a CDN, and faster data fetching."),
    (r"^tbt ",
     "The main thread is blocked by long JavaScript tasks.",
     "TBT <= 200 ms",
     "Reduce/defer JavaScript, code-split heavy components with next/dynamic."),
    (r"speed index",
     "The visible page fills in slowly (Speed Index).",
     "Speed Index <= 3.4 s",
     "Prioritise above-the-fold content and reduce blocking resources."),
    (r"over budget|page weight|many requests|large dom|heavy html",
     "The page is heavier than the performance budget.",
     "Within budget (see Expected value)",
     "Remove unused code/images, compress assets, lazy-load below-the-fold content."),
    (r"render-blocking",
     "A CSS/JS file blocks the first render.",
     "No render-blocking third-party resources; critical CSS only",
     "Load scripts with async/defer or next/script strategy=\"lazyOnload\"; inline critical CSS."),
    (r"unused javascript|unused css",
     "A large share of the downloaded code is not used on this page.",
     "Under 40% unused JS / 50% unused CSS",
     "Code-split with next/dynamic, remove unused libraries, purge unused CSS."),
    (r"not compressed",
     "A text response is served without gzip/brotli compression.",
     "Content-Encoding: br or gzip",
     "Enable compression at the server/CDN (Next.js compress: true)."),
    (r"without long-term caching",
     "Hashed static assets are not cached long-term.",
     "Cache-Control: public, max-age=31536000, immutable",
     "Don't override Next.js caching headers for /_next/static."),
    (r"http/1\.1",
     "The site is served over HTTP/1.1.",
     "HTTP/2 or HTTP/3",
     "Enable HTTP/2+ at the host/CDN."),
    (r"no cdn",
     "No CDN detected in the response headers.",
     "Static assets and pages served through a CDN",
     "Put the site behind a CDN (Netlify/Vercel/Cloudflare)."),
    (r"preconnect",
     "Third-party origins used early are not preconnected.",
     "<link rel=\"preconnect\"> for critical third-party origins",
     "Add preconnect hints for the origins listed."),
    (r"failed requests?$|failed request|failed api call|failed third-party request",
     "A network request made by the page failed.",
     "All requests succeed (HTTP 2xx/3xx)",
     "Fix or remove the failing request shown in Current value."),
    (r"missing /_next asset",
     "A Next.js build asset is missing (often a stale cache / deployment mismatch).",
     "All /_next assets load",
     "Redeploy cleanly and purge the CDN cache."),
    (r"performance score|mobile performance",
     "PageSpeed Insights reports a low mobile performance score.",
     "Performance score 90+",
     "Work through the Core Web Vitals issues for this page."),
    (r"slow server response",
     "The server responded slowly.",
     "Under 1.5 s (ideally < 800 ms)",
     "Cache / statically generate the page and speed up data fetching."),
    (r"page failed to load",
     "The page could not be loaded in the browser test.",
     "Page loads within the timeout",
     "Open the page manually, check console/network errors and server logs."),

    # ------------------------------------------------------------------ Next.js / production
    (r"client component",
     "The page file is a Client Component, so it can't export metadata and ships more JavaScript.",
     "page.tsx as a Server Component",
     "Remove 'use client' from page.tsx and move interactive parts into child client components."),
    (r"no metadata|default \(homepage\) title|without generatemetadata",
     "The route doesn't generate its own metadata, so it inherits the default title/description.",
     "metadata / generateMetadata on every route",
     "Export generateMetadata that builds title, description, canonical and openGraph from the page data."),
    (r"generatestaticparams",
     "A dynamic route has no generateStaticParams, so every page is rendered on request.",
     "generateStaticParams for known slugs",
     "Export generateStaticParams returning all slugs."),
    (r"metadatabase",
     "metadataBase is not set, so relative canonical/Open Graph URLs can't be made absolute.",
     "metadataBase: new URL(SITE_URL) in the root layout",
     "Add metadataBase to the root layout metadata."),
    (r"^no (robots|sitemap|manifest|favicon|icon|apple-icon|opengraph-image|twitter-image) file",
     "A Next.js special metadata file is missing.",
     "The file in app/ (or public/)",
     "Add the special file named in Issue to src/app/."),
    (r"external font stylesheet",
     "Fonts load from an external stylesheet (render-blocking, privacy).",
     "next/font",
     "Load fonts with next/font/google or next/font/local."),
    (r"hard-coded localhost|development url",
     "A development / localhost URL appears in source or HTML.",
     "URLs built from NEXT_PUBLIC_SITE_URL",
     "Replace the hard-coded URL with the environment variable."),
    (r"console\.log",
     "console.log / debugger statements are left in the source.",
     "No debug statements in production code",
     "Remove them, or strip them with compiler.removeConsole."),
    (r"unoptimized|images\.formats",
     "Image optimisation is disabled or AVIF is not enabled.",
     "images: { formats: ['image/avif', 'image/webp'] }, unoptimized false",
     "Update next.config images."),
    (r"poweredbyheader",
     "Next.js sends X-Powered-By: Next.js.",
     "poweredByHeader: false",
     "Set poweredByHeader: false in next.config."),
    (r"duplicate (og:|<meta|meta)",
     "A metadata tag is rendered more than once.",
     "Each meta tag once",
     "Remove manual tags that duplicate the Metadata API output."),
    (r"hydration",
     "React hydration failed or warned: server and client HTML differ.",
     "No hydration warnings",
     "Avoid browser-only values (Date, Math.random, window) during render; fix invalid nesting."),
    (r"uncaught javascript error|console errors",
     "JavaScript errors occur on the page.",
     "No console errors",
     "Fix the error shown in Current value (see the browser console stack trace)."),
    (r"rendered client-side only",
     "Most content only appears after JavaScript runs, so crawlers may miss it.",
     "Main content in the server-rendered HTML",
     "Render content in Server Components / SSG instead of useEffect fetches."),
    (r"favicon|apple-touch-icon|theme-color|site name|manifest",
     "Browser/app metadata is missing or incomplete.",
     "favicon, apple-touch-icon, theme-color, site name and a complete web manifest",
     "Add the missing icon/manifest field via the Next.js special files or metadata."),

    # ------------------------------------------------------------------ mobile
    (r"horizontal scroll|wider than the screen|overflow",
     "Content is wider than the phone screen, causing sideways scrolling or cut-off content.",
     "No element wider than the viewport",
     "Fix the element in Element: max-width: 100%, flex-wrap, overflow-x: auto on tables, avoid fixed widths."),
    (r"text smaller than 12px",
     "Text is too small to read on a phone.",
     "Body text 16 px, never below 12 px",
     "Increase the font-size of the element."),
    (r"font-size < 16px",
     "Form fields with text under 16 px make iPhones zoom in on focus.",
     "16 px font-size on inputs",
     "Set the input font-size to 16px (text-base)."),
    (r"button text is cut off",
     "A button's text is clipped.",
     "Button text fully visible",
     "Allow wrapping or reduce padding/text on small screens."),
    (r"mobile menu|menu button",
     "The mobile navigation is missing or doesn't work correctly.",
     "A menu button with aria-expanded that reveals navigation links on small screens",
     "Fix the mobile menu component."),

    # ------------------------------------------------------------------ third parties
    (r"third-party url (broken|error|timeout|ssl)|third-party resource (broken|error)",
     "A third-party URL used by the page fails (error, timeout or SSL error).",
     "Third-party URLs return HTTP 200",
     "Update or remove the URL; self-host critical resources."),
    (r"third-party url over http|insecure third-party",
     "A third-party URL uses plain http://.",
     "https:// URLs",
     "Switch the URL to https://."),
    (r"many third-party|excessive third-party",
     "The page makes many third-party requests, slowing it down and adding privacy risk.",
     "Under 10 third-party requests per page",
     "Remove unneeded tags, defer analytics with next/script, self-host fonts."),
    (r"youtube iframe",
     "A YouTube iframe loads ~1 MB of JavaScript even if never played.",
     "A click-to-load facade",
     "Use a lite-youtube facade or youtube-nocookie with lazy loading."),
    (r"slow third-party domain",
     "A third-party domain responds slowly.",
     "Third-party responses under 1 s",
     "Defer the vendor's script or replace the vendor."),
]

# Fallbacks by category when no rule matches
CATEGORY_FALLBACK = {
    "status": ("The URL does not respond as expected.", "HTTP 200", "Check the server response for this URL."),
    "images": ("An image on the page has a quality/SEO problem.", "Optimised, described images",
               "Fix the image shown in Element."),
    "links": ("A link on the page has a problem.", "Working, descriptive links", "Fix the link shown in Current value."),
    "accessibility": ("An accessibility rule failed.", "WCAG 2.2 AA compliance",
                      "Follow the rule's help link and fix the listed elements."),
    "axe-core": ("axe-core found an accessibility violation.", "No axe-core violations",
                 "Fix the listed elements; see the help link in Details."),
}

_COMPILED = [(re.compile(p, re.I), d, e, f) for p, d, e, f in RULES]


def guide(check, category=""):
    """-> (description, expected, fix) for an issue name; empty strings when unknown."""
    for rx, d, e, f in _COMPILED:
        if rx.search(check or ""):
            return d, e, f
    fb = CATEGORY_FALLBACK.get((category or "").lower())
    if fb:
        return fb
    return "", "", ""
